"use client";
import { useEffect, useState, useRef, useCallback } from "react";

export interface NodeData {
  id: string; label: string; ip: string;
  temp?: number; humidity?: number; light?: number; gas_ppm?: number;
  gas_explanation?: string;
  mode?: string; seq?: number;
  pktRate: number; trust: number;
  lastSeen: string; online: boolean;
}
export interface PacketEntry  { id: number; time: string; label: string; device: string; iat: number; }
export interface AlertEntry   { id: number; time: string; title: string; severity: "CRITICAL"|"HIGH"|"MEDIUM"|"LOW"; device: string; meta: string; }
export interface TemporalPoint{ t: string; anomaly: number; r1: number; r2: number; r3: number; }
export interface MLState       { label: string; confidence: number; isAttack: boolean; pktRate: number; iatMean: number; dupRatio: number; seqGap: number; shap: {feature:string;value:number;raw:number}[]; }
export interface SensorPoint  { t: string; temp?: number; humidity?: number; light?: number; gas_ppm?: number; }
export interface IncidentState { text: string; label: string; ts: string; }

const ATTACKS = ["DOS_FLOOD", "REPLAY_ATTACK", "SLOW_RATE_ATTACK", "DATA_POISON", "TOPIC_BOMB", "EVASION_ATTACK"];

export function useLiveData() {
  const [nodes, setNodes]       = useState<Record<string, NodeData>>({
    esp32_1: { id:"esp32_1", label:"ESP32_1 · DHT22",    ip:"netguard/device1",  pktRate:0, trust:94, lastSeen:"—", online:false, temp:0,   humidity:0 },
    esp32_2: { id:"esp32_2", label:"ESP32_2 · LDR",      ip:"netguard/device2",  pktRate:0, trust:91, lastSeen:"—", online:false, light:0 },
    esp32_3: { id:"esp32_3", label:"ESP32_3 · Attacker", ip:"netguard/attacker", pktRate:0, trust:95, lastSeen:"—", online:false, mode:"AWAITING", seq:0, gas_ppm: 0, gas_explanation: "Initializing..." },
  });
  const [packets, setPackets]   = useState<PacketEntry[]>([]);
  const [alerts,  setAlerts]    = useState<AlertEntry[]>([]);
  const [temporal,setTemporal]        = useState<TemporalPoint[]>([]);
  const [sensorTemporal,setSensorTemporal] = useState<SensorPoint[]>([]);
  const [ml,      setML]               = useState<MLState>({ label:"AWAITING", confidence:0, isAttack:false, pktRate:0, iatMean:0, dupRatio:0, seqGap:1, shap:[] });
  const [incident, setIncident]        = useState<IncidentState>({ text:"", label:"", ts:"" });
  const [totalPkts,setTotal]           = useState(0);
  const [wsReady, setWsReady]          = useState(false);

  const pktIdRef   = useRef(0);
  const alertIdRef = useRef(0);
  const pktRateRef = useRef<Record<string,number>>({ esp32_1:0, esp32_2:0, esp32_3:0 });

  useEffect(() => {
    let ws: WebSocket;

    function connect() {
      try {
        ws = new WebSocket("ws://localhost:8000/ws/live");

        ws.onopen  = () => { setWsReady(true);  console.log("[WS] Connected"); };
        ws.onclose = () => { setWsReady(false); console.log("[WS] Disconnected, retrying..."); setTimeout(connect, 3000); };
        ws.onerror = (e) => { console.error("[WS] Error", e); ws.close(); };

        ws.onmessage = (e) => {
          const d = JSON.parse(e.data);
          const now = new Date().toLocaleTimeString("en-GB");

          // ── Real ML inference result (every 5s from model) ───────────────
          if (d.topic === "netguard/inference") {
            const isAtk = d.isAttack as boolean;
            setML({
              label:      d.label,
              confidence: d.confidence,
              isAttack:   isAtk,
              pktRate:    d.pkt_rate ?? 0,
              iatMean:    d.iat_mean ?? 0,
              dupRatio:   d.dup_ratio ?? 0,
              seqGap:     d.seq_gap ?? 1,
              shap:       d.shap ?? [],
            });

            // Anomaly score from model confidence
            const anomaly = isAtk ? d.confidence : Math.max(0, 100 - d.confidence);
            setTemporal(t => [...t, {
              t: now, anomaly,
              r1: pktRateRef.current.esp32_1,
              r2: pktRateRef.current.esp32_2,
              r3: pktRateRef.current.esp32_3,
            }].slice(-60));

            if (isAtk) {
              const sev: AlertEntry["severity"] =
                d.label === "DOS_FLOOD" ? "CRITICAL" :
                d.label === "REPLAY_ATTACK" ? "HIGH" : "MEDIUM";
              setAlerts(a => [{
                id: ++alertIdRef.current, time: now,
                title: `${d.label.replace(/_/g," ")} detected on ESP32_3`,
                severity: sev, device: "esp32_3",
                meta: `rate:${d.pkt_rate}pkt/s · iat:${d.iat_mean}ms · dup:${(d.dup_ratio*100).toFixed(0)}% · conf:${d.confidence}%`
              }, ...a].slice(0, 80));
            }
            return;
          }

          // ── Incident narrative (auto-generated by RAG on attack) ──────────
          if (d.topic === "netguard/incident") {
            setIncident({ text: d.text ?? "", label: d.label ?? "", ts: d.ts ?? "" });
            return;
          }

          if (d.topic === "netguard/gas_explanation") {
            setNodes(n => ({
              ...n,
              esp32_3: { ...n.esp32_3, gas_explanation: d.explanation }
            }));
            return;
          }

          // ── Attacker packet — update node card only (ML comes from inference) ──
          if (d.topic === "netguard/attacker") {
            const pktRate = d.pkt_rate ?? 0;
            pktRateRef.current.esp32_3 = pktRate;
            setNodes(n => ({
              ...n,
              esp32_3: { ...n.esp32_3, mode: d.mode, seq: d.seq, pktRate, gas_ppm: d.gas_ppm, lastSeen: now, online: true }
            }));
            if (d.gas_ppm !== undefined) {
              setSensorTemporal(s => [...s, { t: now, gas_ppm: d.gas_ppm }].slice(-80));
            }
            const entry: PacketEntry = { id: ++pktIdRef.current, time: now, label: d.mode, device: "netguard/attacker", iat: 0 };
            setPackets(p => [entry, ...p].slice(0, 120));
            setTotal(p => p + 1);
          }

          else if (d.topic === "netguard/device1") {
            pktRateRef.current.esp32_1 = +(pktRateRef.current.esp32_1 * 0.8 + 0.5).toFixed(1);
            setNodes(n => ({ ...n, esp32_1: { ...n.esp32_1, temp: d.temp, humidity: d.humidity, pktRate: +pktRateRef.current.esp32_1.toFixed(1), lastSeen: now, online: true } }));
            setSensorTemporal(s => [...s, { t: now, temp: d.temp, humidity: d.humidity }].slice(-80));
            const entry: PacketEntry = { id: ++pktIdRef.current, time: now, label:"LEGITIMATE", device:"netguard/device1", iat:0 };
            setPackets(p => [entry, ...p].slice(0, 120));
            setTotal(p => p + 1);
          }

          // ── LDR packet ───────────────────────────────────────────────────
          else if (d.topic === "netguard/device2") {
            pktRateRef.current.esp32_2 = +(pktRateRef.current.esp32_2 * 0.8 + 0.5).toFixed(1);
            setNodes(n => ({ ...n, esp32_2: { ...n.esp32_2, light: d.light, pktRate: +pktRateRef.current.esp32_2.toFixed(1), lastSeen: now, online: true } }));
            setSensorTemporal(s => [...s, { t: now, light: d.light }].slice(-80));
            const entry: PacketEntry = { id: ++pktIdRef.current, time: now, label:"LEGITIMATE", device:"netguard/device2", iat:0 };
            setPackets(p => [entry, ...p].slice(0, 120));
            setTotal(p => p + 1);
          }
        };
      } catch(err) {
        console.error("[WS] Failed to connect:", err);
        setTimeout(connect, 3000);
      }
    }

    connect();
    return () => { try { ws?.close(); } catch {} };
  }, []);

  const triggerAttack = useCallback(async (mode: string) => {
    try {
      await fetch("http://localhost:8000/attacker/mode", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ mode }),
      });
    } catch (e) {
      console.error("Backend offline:", e);
    }
  }, []);

  const simulate = useCallback(async (mode: string) => {
    try {
      await fetch("http://localhost:8000/simulate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ mode }),
      });
    } catch (e) {
      console.error("Simulate offline:", e);
    }
  }, []);

  return { nodes, packets, alerts, temporal, sensorTemporal, ml, incident, totalPkts, wsReady, triggerAttack, simulate };
}
